### ISSUE TITLE
Integration via Swift Package Manager fails with "has no Package.swift manifest"

### ISSUE THREAD

**Issue by scalessec** [AppsFlyerSDK/AppsFlyerFramework#189]
# Report

## SDK Version

I can repro with `4.6.2` and `4.6.1`. I haven't tried older releases. I'm using Xcode 13.1 (13A1030d).

## What did you do?

I followed the Swift Package Manager instructions exactly as they are written in the README.

## What did you expect to happen?

For the package to be added. 

## What happened instead?

The package fails to be added. The error is:
`/Package.swift has no Package.swift manifest for version 4.6.1 in https://github.com/AppsFlyerSDK/AppsFlyerFramework`

## Please provide any other relevant information.

This is the error you'd typically receive if the `Package.swift` file was missing from the root directory. This is obviously not the case in this scenario, so I'm unsure why this would be happening.

**Comment by af-obodovskyi** [comment]
@scalessec, hi, the versions, you have mentioned not support SPM.

**Comment by joshuapoq** [comment]
Not sure if it's related but we are also seeing issues with the latest hotfix and no issues on `4.6.0`. I don't see how your PR addresses any issue here though unless the `Package.swift` has some weird character.

The errors we are seeing are as follows which I thought might be related to Xcode 13 (as specified in the release notes). But it is odd that this issue is only caused by the latest hotfix. I believe something is wrong with the xcframework.
```
❌  /.../SourcePackages/checkouts/Poq.iOS.AppsFlyer/Sources/AppsFlyerModule.swift:9:8: no such module 'AppsFlyerLib'
```

**Comment by scalessec** [comment]
Regarding the PR, TIL that trailing commas are valid swift syntax. For whatever reason though, the manifest is found on the PR branch and not found on the official tag so it might very well be some invalid/hidden character.
