### ISSUE TITLE
6.14.0 - SPM checksum does not match

### ISSUE THREAD

**Issue by scottlemke** [AppsFlyerSDK/AppsFlyerFramework#279]
# Report
When integrating version `6.14.0` of the Appsflyer SDK via SPM, I receive the following error:
`checksum of downloaded artifact of binary target 'AppsFlyerLib' (e3063f25dd58b242c31d1bc5761fcb96930539e8e4d0745c22df792ecbd455e0) does not match checksum specified by the manifest (d7fdf61996dacb7787506305b6c541197ede64fcc4528c41842d9a507bd1b94b)`

## SDK Version

6.14.0

## What did you do?

Add the Appsflyer SDK Package Dependency in Xcode.

## What did you expect to happen?

The package is added successfully.

## What happened instead?

An error is displayed by Swift Package Manager: `checksum of downloaded artifact of binary target 'AppsFlyerLib' (e3063f25dd58b242c31d1bc5761fcb96930539e8e4d0745c22df792ecbd455e0) does not match checksum specified by the manifest (d7fdf61996dacb7787506305b6c541197ede64fcc4528c41842d9a507bd1b94b)`

## Please provide any other relevant information.

NA

**Comment by RonKliffer** [comment]
@scottlemke I had the same issue, resolved it by removing the cache. Do:
rm -rf ~/Library/Caches/org.swift.swiftpm
rm -rf ~/Library/org.swift.swiftpm
rm -rf ~/.swiftpm

Also delete derived data and optionally delete Package.resolved file.

**Comment by scottlemke** [comment]
I've already tried this and still get the same error. You can manually verify by download the zip file that is specified in the Package.swift file and calculating the checksum. It does not match the one specified in the file.

**Comment by af-obodovskyi** [comment]
@scottlemke Please consider using one of the following repositories for the SPM. SPM support will be removed from the main repository because of the extremely long checkout time, which affects the release process. 

For statically linked library
https://github.com/AppsFlyerSDK/AppsFlyerFramework-Static

For dynamically linked library
https://github.com/AppsFlyerSDK/AppsFlyerFramework-Dynamic

For Strict (No IDFA colection) library
https://github.com/AppsFlyerSDK/AppsFlyerFramework-Strict
