### ISSUE TITLE
iOS 12 Support

### ISSUE THREAD

**Issue by zmian** [AppsFlyerSDK/AppsFlyerFramework#72]
iOS 12 added a new overlay for [UIUserActivityRestoring](https://developer.apple.com/documentation/uikit/uiuseractivityrestoring) and it is incompatible with the current signature of `AppsFlyerTracker.frameowork`

```swift
// AppsFlyer method signature
AppsFlyerTracker.shared()?.continue(userActivity: NSUserActivity!, restorationHandler: (([Any]?) -> Void)!)

// iOS 12 method signature
func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
```

As you can see from the `restorationHandler`  handler needs to be updated. Any idea how the migration would work?

**Comment by andr-ggn** [comment]
Hello, @zmian!
Thank you for your request, we appreciate it. You can use the same API for `continue userActivity` because we receive the `restorationHandler` but not using it internally so it does not break a thing

For Objective-C:
![screen shot 2018-08-27 at 11 13 17](https://user-images.githubusercontent.com/4691004/44648820-e6894f80-a9ea-11e8-8267-72c04bbf9f79.png)

For Swift you can pass a `nil`
![screen shot 2018-08-27 at 11 35 37](https://user-images.githubusercontent.com/4691004/44649770-7a5c1b00-a9ed-11e8-90b8-eb66eaccb884.png)



Andrey

**Comment by zmian** [comment]
Thank you @andr-ggn
